version: '3'
services:
  db:
    image: mariadb:10.3
    ports:
      - "6666:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=4kuC1ntaBangsay
      - MYSQL_DATABASE=form
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sql/db.sql:/docker-entrypoint-initdb.d/dump.sql
    container_name: form-db
  api:
    build:
      context: ./src/api
    volumes:
      - "./src/api:/src/api"
      - "./conf/reflex.conf:/src/api/reflex.conf"
    working_dir: /src/api
    command: >
      bash -c "reflex -c reflex.conf"
    ports:
      - "6789:6789"
    tty: true
    depends_on:
      - web
    container_name: form-api
  web:
    image: nginx
    depends_on:
      - db
    ports:
      - "6969:80"
    volumes:
      - ./src/frontend:/src/frontend
      - ./conf/nginx.conf:/etc/nginx/conf.d/app.conf
      - ./log:/var/log/nginx
    container_name: form-web    
