version: '3'
services:
  db:
    image: mariadb:10.3
    ports:
      - "6666:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pl3rk3TecUck
      - MYSQL_DATABASE=starter
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sql/db.sql:/docker-entrypoint-initdb.d/dump.sql
    container_name: starter-db
  php:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    volumes:
      - ./src/frontend:/src/frontend
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    container_name: starter-php
  api:
    build:
      context: ./src/api
    volumes:
      - "./src/api:/src/api"
      - "./conf/reflex.conf:/src/api/reflex.conf"
    working_dir: /src/api
    command: >
      bash -c "reflex -c reflex.conf"
    ports:
      - "6789:6789"
    tty: true
    depends_on:
      - db
    container_name: starter-api
  web:
    image: nginx
    depends_on:
      - php
    ports:
      - "6969:80"
    volumes:
      - ./src/frontend:/src/frontend
      - ./conf/nginx.conf:/etc/nginx/conf.d/app.conf
      - ./log:/var/log/nginx
    container_name: starter-web    
